import { Mail, MessageSquare, X } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";

interface ReportPreviewProps {
  isOpen: boolean;
  onClose: () => void;
  summary: {
    total_reviews: number;
    positive_count: number;
    neutral_count: number;
    negative_count: number;
    top_complaints: string[];
    top_features: string[];
    daily_summary: string;
  };
  date: string;
}

export function ReportPreview({
  isOpen,
  onClose,
  summary,
  date,
}: ReportPreviewProps) {
  const currentTime = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const emailHTML = `
    <div style="font-family: 'Inter', Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333;">
      <div style="background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%); padding: 32px; border-radius: 16px 16px 0 0;">
        <h1 style="color: #ffffff; margin: 0; font-size: 26px; font-weight: 700;">📊 Play Store Review Intelligence Report</h1>
        <p style="color: #E0E7FF; margin: 8px 0 0; font-size: 15px; font-weight: 500;">${date}</p>
      </div>
      <div style="background: #ffffff; padding: 32px; border: 1px solid #E5E7EB; border-top: none;">
        <h2 style="color: #6366F1; border-bottom: 3px solid #EDE9FE; padding-bottom: 10px; margin-top: 0; font-weight: 700;">Executive Summary</h2>
        <p style="line-height: 1.8; font-size: 15px; color: #4B5563;">${summary.daily_summary}</p>
        
        <h2 style="color: #6366F1; border-bottom: 3px solid #EDE9FE; padding-bottom: 10px; margin-top: 32px; font-weight: 700;">Review Statistics</h2>
        <table style="width: 100%; border-collapse: collapse; margin-top: 16px;">
          <tr style="background: #F3F4F6;">
            <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Metric</th>
            <th style="padding: 12px 16px; text-align: center; font-weight: 600; color: #374151;">Count</th>
          </tr>
          <tr style="border-bottom: 1px solid #E5E7EB;">
            <td style="padding: 12px 16px; color: #4B5563;">Total Reviews Analyzed</td>
            <td style="text-align: center; font-weight: 700; color: #1F2937;">${summary.total_reviews}</td>
          </tr>
          <tr style="background: #F0FDF4; border-bottom: 1px solid #E5E7EB;">
            <td style="padding: 12px 16px; color: #166534; font-weight: 500;">✅ Positive</td>
            <td style="text-align: center; color: #16A34A; font-weight: 700;">${summary.positive_count}</td>
          </tr>
          <tr style="border-bottom: 1px solid #E5E7EB;">
            <td style="padding: 12px 16px; color: #9A3412; font-weight: 500;">➖ Neutral</td>
            <td style="text-align: center; color: #EA580C; font-weight: 700;">${summary.neutral_count}</td>
          </tr>
          <tr style="background: #FEF2F2;">
            <td style="padding: 12px 16px; color: #991B1B; font-weight: 500;">❌ Negative</td>
            <td style="text-align: center; color: #DC2626; font-weight: 700;">${summary.negative_count}</td>
          </tr>
        </table>
        
        <h2 style="color: #6366F1; border-bottom: 3px solid #EDE9FE; padding-bottom: 10px; margin-top: 32px; font-weight: 700;">Top User Complaints</h2>
        <ol style="line-height: 1.8; font-size: 15px; color: #4B5563; padding-left: 20px;">
          ${summary.top_complaints.map((c) => `<li style="margin-bottom: 8px;">${c}</li>`).join("")}
        </ol>
        
        <h2 style="color: #6366F1; border-bottom: 3px solid #EDE9FE; padding-bottom: 10px; margin-top: 32px; font-weight: 700;">Top Appreciated Features</h2>
        <ol style="line-height: 1.8; font-size: 15px; color: #4B5563; padding-left: 20px;">
          ${summary.top_features.map((f) => `<li style="margin-bottom: 8px;">${f}</li>`).join("")}
        </ol>
      </div>
      <div style="background: linear-gradient(135deg, #EDE9FE 0%, #DDD6FE 100%); padding: 20px 32px; border-radius: 0 0 16px 16px; text-align: center;">
        <p style="margin: 0; font-size: 13px; color: #6366F1; font-weight: 500;">This report was automatically generated by the Play Store Review Intelligence System · ${currentTime} IST</p>
      </div>
    </div>
  `;

  const slackMessage = `📊 *Play Store Review Daily Digest — ${date}*

📝 *Executive Summary*
${summary.daily_summary}

📈 *Review Stats*
• Total: *${summary.total_reviews}* reviews
• ✅ Positive: *${summary.positive_count}*
• ➖ Neutral: *${summary.neutral_count}*
• ❌ Negative: *${summary.negative_count}*

⚠️ *Top Complaints*
${summary.top_complaints.map((c, i) => `${i + 1}. ${c}`).join("\n")}

⭐ *Top Appreciated Features*
${summary.top_features.map((f, i) => `${i + 1}. ${f}`).join("\n")}

_Auto-generated by Play Store Review Intelligence System_`;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Mail className="w-5 h-5 text-purple-600" />
            Report Preview
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="email" className="w-full">
          <TabsList className="grid w-full grid-cols-2 bg-purple-100">
            <TabsTrigger value="email" className="flex items-center gap-2 data-[state=active]:bg-purple-600 data-[state=active]:text-white rounded-lg font-semibold">
              <Mail className="w-4 h-4" />
              Email Report
            </TabsTrigger>
            <TabsTrigger value="slack" className="flex items-center gap-2 data-[state=active]:bg-purple-600 data-[state=active]:text-white rounded-lg font-semibold">
              <MessageSquare className="w-4 h-4" />
              Slack Message
            </TabsTrigger>
          </TabsList>

          <TabsContent value="email" className="mt-4">
            <div className="bg-gray-50 p-5 rounded-xl">
              <div className="bg-white rounded-lg shadow-sm mb-4 p-4 border border-gray-200">
                <div className="text-sm font-semibold text-gray-700">To:</div>
                <div className="text-sm text-gray-600 mt-1">
                  krishnarawat.business@gmail.com
                </div>
                <div className="text-sm font-semibold text-gray-700 mt-3">
                  Subject:
                </div>
                <div className="text-sm text-gray-600 mt-1">
                  [REVIEW REPORT] Play Store Daily Digest — {date}
                </div>
              </div>
              <div
                className="bg-white rounded-lg shadow-sm overflow-auto"
                dangerouslySetInnerHTML={{ __html: emailHTML }}
              />
            </div>
          </TabsContent>

          <TabsContent value="slack" className="mt-4">
            <div className="bg-gray-50 p-5 rounded-xl">
              <div className="bg-white rounded-lg shadow-sm mb-4 p-4 border border-gray-200">
                <div className="text-sm font-semibold text-gray-700">
                  Channel:
                </div>
                <div className="text-sm text-gray-600 mt-1">
                  #all-product-review
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-6 border border-gray-200">
                <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-gray-700">
                  {slackMessage}
                </pre>
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <div className="flex justify-end gap-3 mt-4 pt-4 border-t">
          <Button variant="outline" onClick={onClose} className="rounded-full font-semibold">
            Close
          </Button>
          <Button className="rounded-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 font-semibold">
            <Mail className="w-4 h-4 mr-2" />
            Send Report
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
